### ISSUE TITLE
Deleting and then restoring a .d.ts file leads to type errors

### ISSUE THREAD

**Issue by stowellt** [TypeStrong/fork-ts-checker-webpack-plugin#21] opened 2017-06-09 16:02 UTC
To reproduce:

1. Use the Webpack Dev Server
2. Make sure the config includes ts-loader with transpileOnly = true, and the fork-ts-checker-webpack-plugin
3. Delete a .d.ts file that declares an interface some other .ts file uses
4. Save a .ts file to trigger recompilation
5. You should see an type error about the missing interface that was declared in the .d.ts file
6. Re-add the .d.ts file that was deleted
7. Re-save the .ts file again to trigger recompilation
8. You will still see the same error even though the .d.ts file has been restored

It seems like this is a caching bug. If I use ts-loader with transpileOnly = false, and if I don't use this plugin, then the issue goes away

**Comment by piotr-oles** [comment] 2017-06-11 08:47
I've replayed your scenario and I don't have this issue. Please send me your `tsconfig.json` file - it could be the reason - see https://github.com/Realytics/fork-ts-checker-webpack-plugin#modules-resolution

**Comment by stowellt** [comment] 2017-06-12 14:46
The tsconfig file is pretty simple:

`{
  "compileOnSave": true,
  "compilerOptions": {
    "module": "es2015",
    "sourceMap": true,
    "target": "es5",
    "moduleResolution": "node"
  }
}`

I've tried setting "moduleResolution" to "classic", but the same issue persists. What version of Typescript are you testing with? I'm using 2.3.4

**Comment by stowellt** [comment] 2017-06-12 18:33
Update: I found the issue is solved for me if I comment out lines 96 & 98 in IncrementalChecker.js so the following statement is always executed:

`this.programConfig = IncrementalChecker.loadProgramConfig(this.programConfigFile);`

I realize that isn't a permanent solution, but is there any way to update the file list on every run of IncrementalChecker.prototype.nextIteration? If someone else on my team adds a new .d.ts file to Git and I pull to get the changes, I'll get a type error from this plugin because it's not aware of the newly added file. The only current fix is to stop and restart Webpack.

**Comment by piotr-oles** [comment] 2017-06-16 05:54
Sorry for the delay, I have exams at a college so I'm a little bit busy :/
It's very weird - typescript uses an old program to build a new one but there are checks for program reusability inside typescript compiler.
I would like to help you but as long I can't reproduce the bug, I can't fix it. I've used 2.3.4 too.
Could you create a repository for issue reproduction? Or if it's an open source, just send me a link, please :)

**Comment by piotr-oles** [comment] 2017-07-08 19:20
@stowellt ? :)

**Comment by stowellt** [comment] 2017-07-10 14:08
I apologize for the delay in response. The project is proprietary so I can't send a link. I haven't had time to setup a repo to reproduce the issue, and unfortunately it might be a while before I will have a chance to do that. I understand if you want to close this bug. I would still like to revisit this in the future at some point though, thanks.

**Comment by piotr-oles** [comment] 2017-07-14 07:07
No problem :) Thank you for reporting, I will close this issue :) Feel free to re-open issue in the future ;)

**Closed as completed by piotr-oles** 2017-07-14 07:07 UTC
Labels: bug
