### ISSUE TITLE
Documentation clarification of topic "Modules Resolution"?

### ISSUE THREAD

**Issue by JasonKleban** [TypeStrong/fork-ts-checker-webpack-plugin#592] opened 2021-04-20 14:52 UTC
> It's very important to be aware that this plugin uses TypeScript's, not webpack's modules resolution. It means that you have to setup tsconfig.json correctly. For example if you set files: `['./src/index.ts']` in `tsconfig.json`, this plugin will check only `index.ts` for errors.

-- https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#modules-resolution

Does this mean that imports of index.ts will not be explored/checked?  That was my initial interpretation, but then that behavior wouldn't match typescript's module resolution either - it would be basically _no_ module resolution.  I guess if `build: true` it would match, but if `build: false` then `files` array is just the entry points for the transpilation graph.

I'm trying to debug a build issue, and I need to gain confidence on this point, please.  I'm running forked v6.2.1 and not getting any errors listed.  Kind of like https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/319 except that's claimed to be fixed in v6.

**Comment by piotr-oles** [comment] 2021-04-21 06:24
That's a good point - you're right, we should update the doc :) Would you like to create a PR to update it?

**Comment by JasonKleban** [comment] 2021-04-21 11:23
Thanks!  But I don't know the complete correct answer to know what to replace it with.

**Comment by piotr-oles** [comment] 2021-04-21 17:57
The plugin will use the same module resolution as TypeScript. The simplest option to check whether it's a configuration issue or a bug in the plugin is running the `tsc` command - in your case, it should be `tsc --build --watch`. If it works in TypeScript, then the issue is in the plugin, otherwise, the issue is in the configuration or TypeScript itself :)

**Comment by piotr-oles** [comment] 2021-04-21 19:36
I will close this issue - if you find any problems with the build mode, please open another one with a description and reproduction repository :)

**Closed as completed by piotr-oles** 2021-04-21 19:36 UTC
Labels: bug
