### ISSUE TITLE
Cannot find module issue while using on a webpack.config.TS file

### ISSUE THREAD

**Issue by junalmeida** [TypeStrong/fork-ts-checker-webpack-plugin#359] opened 2019-11-21 15:06 UTC
## Current behavior
![image](https://user-images.githubusercontent.com/991675/69349766-f5869e00-0c3d-11ea-86aa-4edeeba40d77.png)

## Expected behavior
Typings should be found by the editor.

## Steps to reproduce the issue
Add package and run `yarn install`

## Issue reproduction repository
None yet

## Environment
 - **fork-ts-checker-webpack-plugin**: 3.1.0
 - **typescript**: 3.7.2
 - **tslint**: 5.14.0
 - **webpack**: 4.29.0
 - **os**: Windows

**Comment by phryneas** [comment] 2019-11-21 22:07
This means that the TSServer run by your IDE cannot find fork-ts-checker-webpack-plugin. This can have plenty of reasons (most likely misconfiguration of `moduleResolution`, `typeRoots` or `types` in your `tsconfig.json` - or it is actually not installed), but it definitely is not a bug of fork-ts-checker-webpack-plugin.

Please re-check your setup, and if you really can't resolve this create a reproducible minimal repository so we can help you fix it.

**Comment by junalmeida** [comment] 2019-11-22 14:28
@phryneas ok, let me show you my setup: 

`package.json`
![image](https://user-images.githubusercontent.com/991675/69433673-a013c500-0d01-11ea-9000-e03b897ffa36.png)

`node-modules`
![image](https://user-images.githubusercontent.com/991675/69433717-c174b100-0d01-11ea-8a77-bba46d37fc18.png)

`tsconfig.json`

```
"module": "commonjs",
"target": "es5",
"moduleResolution": "node",
"typeRoots": [ "./node_modules/@types", "./Content/src/custom_typings" ]
```
There is no `types` node.

**Comment by piotr-oles** [comment] 2020-05-23 19:46
@junalmeida
Please try [fork-ts-checker-webpack-plugin@alpha](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/alpha) - I've published a new version which should resolve this issue 🚀
I will close this issue to clean-up the backlog. If this release didn't solve the issue, we can re-open this :)

**Closed as completed by piotr-oles** 2020-05-23 19:46 UTC
Labels: bug
