### ISSUE TITLE
Add "onlyCheckBundledFiles" option to enable checking files which actually bundled by webpack only

### ISSUE THREAD

**Issue by eagleliang** [TypeStrong/fork-ts-checker-webpack-plugin#543] opened 2020-11-26 06:10 UTC
## Feature motivation
As webpack will analyse the dependency and only pack the actually files in bundle, addtional file settings(`include` `files` and `exclude`) of tsconfig.json is redundant in a sense. 

I'd like to have a option to make the type checking only check the files which be bundled. With this option, I can switch between default behavior and  'only check bundled files' behavior.

This is meaningful for some complex project which use one code repo to pack different implementation versions by different webpack config. In these case, some .ts file is only implemented for one specifial version, and it has the same name with the one in other versions.  If it's impossible to config with tsconfig.json, the current/default behavior of checker will cause typechecking failure. But in bundled files view, the type checking is pass really.

## Feature description
This option modify the default behavior of checking. Like [ts-loader option](https://github.com/TypeStrong/ts-loader#onlycompilebundledfiles), when this option set to true, the checking won't respect the `include` `files` and `exclude` options in tsconfig.json.

It will simplify the maintainance of the project. In another hand, this feature will accelerate type checking process. 

## Feature implementation

(PS: sorry about my English, wish I make it clear)

**Comment by scamden** [comment] 2021-03-17 19:42
i actually think it was doing this by default as of version 6.0.8, but when we updated to 6.1.1 suddenly it's type checking our test files (which are not included in the webpack bundle) and failing due to a lack of Jest types. 

@eagleliang @piotr-oles  could this actually be a regression?

**Comment by scamden** [comment] 2021-03-17 19:47
or maybe it was previously somehow including the jest types automatically and now isn't? either way the behavior changed between those two versions

**Comment by piotr-oles** [comment] 2021-03-17 20:04
If you want to exclude some directories from type-checking, you can use ‘configOverwrite’ option and add directories to 'exclude' list :)

**Comment by scamden** [comment] 2021-03-17 20:10
@piotr-oles totally i get that.

 i'm just confused what changed because previously our test files were either not being included (which would make sense with only bundle files being included), or somehow the jest types were included alongside them and are not now. i'm just wondering which it is and if either is a regression bug?

**Comment by piotr-oles** [comment] 2021-03-17 20:18
No, it's not. It's a fix for an issue when type-only files were not part of the web pack compilation, therefore if you changed something in type-only file it didn't trigger type-check. Starting from version 5 we add all files from typescript project as webpack dependencies.

**Comment by scamden** [comment] 2021-03-17 20:48
@piotr-oles thanks for the update. apologies for the noise. it looks like the error happens on 6.0.8 as well so it must be due to jest types somehow not being included for another reason. not on you guys.

**Comment by piotr-oles** [comment] 2021-03-18 22:32
@eagleliang I'm closing this issue because I don't think I will implement it. You can manually control the list of type-checked files by overwriting the `include` and `exclude` list :)

**Closed as completed by piotr-oles** 2021-03-18 22:32 UTC
Labels: enhancement

**Comment by MBelniak** [comment] 2022-09-01 15:13
> @eagleliang I'm closing this issue because I don't think I will implement it. You can manually control the list of type-checked files by overwriting the `include` and `exclude` list :)

Yes, but not really conveniently - if we want to type-check only the files which are bundled it's not trivial to do it via `include` and `exclude`. This feature would be really helpful. For example, imagine you may have some devDependency installed into node_modules which has TS code incompatible with the target environment of your lib. You won't bundle this dependency, but still get errors like `Import assignment cannot be used when targeting ECMAScript modules`. Excluding each such dependency via 'exclude' is cumbersome.

**Comment by MBelniak** [comment] 2022-09-01 17:41
My colleague found https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/714 and it seems to achieve what we want :)
