### ISSUE TITLE
TypeError: Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by kodemi** [TypeStrong/fork-ts-checker-webpack-plugin#118] opened 2018-05-17 08:50 UTC
Webpack v.4.8.3
Typescript v.2.3.4

```
D:\Projects\pl-webpack4\node_modules\fork-ts-checker-webpack-plugin\lib\index.js:130
        return path.isAbsolute(filePath) ? filePath : path.resolve(this.compiler.options.context, filePath);

                                                                                        ^
TypeError: Cannot read property 'context' of undefined

   at ForkTsCheckerWebpackPlugin.computeContextPath (D:\Projects\pl-webpack4\node_modules\fork-ts-checker-webpack-plugin\lib\index.js:130:89)
    at ForkTsCheckerWebpackPlugin.apply (D:\Projects\pl-webpack4\node_modules\fork-ts-checker-webpack-plugin\lib\index.js:86:34)
    at plugins.forEach.plugin (D:\Projects\pl-webpack4\node_modules\enhanced-resolve\lib\ResolverFactory.js:276:10)
    at Array.forEach (<anonymous>)
    at Object.exports.createResolver (D:\Projects\pl-webpack4\node_modules\enhanced-resolve\lib\ResolverFactory.js:275:10)
    at ResolverFactory._create (D:\Projects\pl-webpack4\node_modules\webpack\lib\ResolverFactory.js:57:28)
    at ResolverFactory.get (D:\Projects\pl-webpack4\node_modules\webpack\lib\ResolverFactory.js:50:28)
    at Compilation.buildModule (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compilation.js:365:25)
    at moduleFactory.create (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compilation.js:711:12)
    at MultiModuleFactory.create (D:\Projects\pl-webpack4\node_modules\webpack\lib\MultiModuleFactory.js:18:3)
    at semaphore.acquire (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compilation.js:658:18)
    at Semaphore.acquire (D:\Projects\pl-webpack4\node_modules\webpack\lib\util\Semaphore.js:17:4)
    at Compilation._addModuleChain (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compilation.js:657:18)
    at Compilation.addEntry (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compilation.js:741:8)
    at compiler.hooks.make.tapAsync (D:\Projects\pl-webpack4\node_modules\webpack\lib\MultiEntryPlugin.js:41:17)
    at AsyncParallelHook.eval [as callAsync] (eval at create (D:\Projects\pl-webpack4\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncParallelHook.lazyCompileHook [as _callAsync] (D:\Projects\pl-webpack4\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at hooks.beforeCompile.callAsync.err (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compiler.js:476:20)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Projects\pl-webpack4\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\Projects\pl-webpack4\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at Compiler.compile (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compiler.js:469:28)
    at readRecords.err (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compiler.js:220:11)
    at Compiler.readRecords (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compiler.js:342:11)
    at hooks.run.callAsync.err (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compiler.js:217:10)
    at _err0 (eval at create (D:\Projects\pl-webpack4\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:11:1)
    at compiler.hooks.run.tapAsync (D:\Projects\pl-webpack4\node_modules\webpack\lib\CachePlugin.js:46:60)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Projects\pl-webpack4\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\Projects\pl-webpack4\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at hooks.beforeRun.callAsync.err (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compiler.js:214:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Projects\pl-webpack4\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
```

If I set absolute path to tsconfig in options, than:
```
D:\Projects\pl-webpack4\node_modules\fork-ts-checker-webpack-plugin\lib\index.js:144
            this.compiler.hooks.run.tapAsync(checkerPluginName, run);

                                   ^
TypeError: Cannot read property 'tapAsync' of undefined
    at ForkTsCheckerWebpackPlugin.pluginStart (D:\Projects\pl-webpack4\node_modules\fork-ts-checker-webpack-plugin\lib\index.js:144:36)
    at ForkTsCheckerWebpackPlugin.apply (D:\Projects\pl-webpack4\node_modules\fork-ts-checker-webpack-plugin\lib\index.js:102:18)
    at plugins.forEach.plugin (D:\Projects\pl-webpack4\node_modules\enhanced-resolve\lib\ResolverFactory.js:276:10)
    at Array.forEach (<anonymous>)
    at Object.exports.createResolver (D:\Projects\pl-webpack4\node_modules\enhanced-resolve\lib\ResolverFactory.js:275:10)
    at ResolverFactory._create (D:\Projects\pl-webpack4\node_modules\webpack\lib\ResolverFactory.js:57:28)
    at ResolverFactory.get (D:\Projects\pl-webpack4\node_modules\webpack\lib\ResolverFactory.js:50:28)
    at Compilation.buildModule (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compilation.js:365:25)
    at moduleFactory.create (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compilation.js:711:12)
    at MultiModuleFactory.create (D:\Projects\pl-webpack4\node_modules\webpack\lib\MultiModuleFactory.js:18:3)
    at semaphore.acquire (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compilation.js:658:18)
    at Semaphore.acquire (D:\Projects\pl-webpack4\node_modules\webpack\lib\util\Semaphore.js:17:4)
    at Compilation._addModuleChain (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compilation.js:657:18)
    at Compilation.addEntry (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compilation.js:741:8)
    at compiler.hooks.make.tapAsync (D:\Projects\pl-webpack4\node_modules\webpack\lib\MultiEntryPlugin.js:41:17)
    at AsyncParallelHook.eval [as callAsync] (eval at create (D:\Projects\pl-webpack4\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncParallelHook.lazyCompileHook [as _callAsync] (D:\Projects\pl-webpack4\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at hooks.beforeCompile.callAsync.err (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compiler.js:476:20)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Projects\pl-webpack4\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\Projects\pl-webpack4\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at Compiler.compile (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compiler.js:469:28)
    at readRecords.err (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compiler.js:220:11)
    at Compiler.readRecords (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compiler.js:342:11)
    at hooks.run.callAsync.err (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compiler.js:217:10)
    at _err0 (eval at create (D:\Projects\pl-webpack4\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:11:1)
    at compiler.hooks.run.tapAsync (D:\Projects\pl-webpack4\node_modules\webpack\lib\CachePlugin.js:46:60)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Projects\pl-webpack4\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\Projects\pl-webpack4\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at hooks.beforeRun.callAsync.err (D:\Projects\pl-webpack4\node_modules\webpack\lib\Compiler.js:214:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Projects\pl-webpack4\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
```

**Comment by deftomat** [comment] 2018-06-10 10:30
@kodemi Did you solve this issue?

**Comment by ibuchan72390** [comment] 2018-06-13 23:08
I was encountering this issue on rebuild after I implemented the fork-ts-checker-webpack-plugin.  I had recently switched from awesome-typescript-loader to ts-loader with transpileOnly: true.  I was having absurdly slow build times and had implemented the SpeedMeasurePlugin a while back to try and uncover the slow process.  While I was able to see a 90% improvement in build time, the SpeedMeasurePlugin was killing rebuilds.

```
TypeError: Cannot read property 'callAsync' of undefined
    at Proxy.<anonymous> (D:\Workspaces\iam-global-education\src\UI\IAGE.School.UI.Web\node_modules\fork-ts-checker-webpack-plugin\lib\index.js:222:69)
    at D:\Workspaces\iam-global-education\src\UI\IAGE.School.UI.Web\node_modules\speed-measure-webpack-plugin\WrappedPlugin\index.js:52:19
    at SyncHook.eval (eval at create (D:\Workspaces\iam-global-education\src\UI\IAGE.School.UI.Web\node_modules\tapable\lib\HookCodeFactory.js:17:12), <anonymous>:7:1)
    at hooks.beforeCompile.callAsync.err (D:\Workspaces\iam-global-education\src\UI\IAGE.School.UI.Web\node_modules\webpack\lib\Compiler.js:472:23)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Workspaces\iam-global-education\src\UI\IAGE.School.UI.Web\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at Compiler.compile (D:\Workspaces\iam-global-education\src\UI\IAGE.School.UI.Web\node_modules\webpack\lib\Compiler.js:469:28)
    at compiler.hooks.watchRun.callAsync.err (D:\Workspaces\iam-global-education\src\UI\IAGE.School.UI.Web\node_modules\webpack\lib\Watching.js:77:18)
    at _err (eval at create (D:\Workspaces\iam-global-education\src\UI\IAGE.School.UI.Web\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:29:1)
    at func.apply.argsButLast.map.concat (D:\Workspaces\iam-global-education\src\UI\IAGE.School.UI.Web\node_modules\speed-measure-webpack-plugin\WrappedPlugin\index.js:44:9)
    at Proxy.watchRun (D:\Workspaces\iam-global-education\src\UI\IAGE.School.UI.Web\node_modules\fork-ts-checker-webpack-plugin\lib\index.js:140:13)
    at D:\Workspaces\iam-global-education\src\UI\IAGE.School.UI.Web\node_modules\speed-measure-webpack-plugin\WrappedPlugin\index.js:40:16
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Workspaces\iam-global-education\src\UI\IAGE.School.UI.Web\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)
    at Watching._go (D:\Workspaces\iam-global-education\src\UI\IAGE.School.UI.Web\node_modules\webpack\lib\Watching.js:40:32)
    at Watching._invalidate (D:\Workspaces\iam-global-education\src\UI\IAGE.School.UI.Web\node_modules\webpack\lib\Watching.js:164:9)
    at watcher.compiler.watchFileSystem.watch (D:\Workspaces\iam-global-education\src\UI\IAGE.School.UI.Web\node_modules\webpack\lib\Watching.js:135:10)
    at EventEmitter.watcher.once (D:\Workspaces\iam-global-education\src\UI\IAGE.School.UI.Web\node_modules\webpack\lib\node\NodeWatchFileSystem.js:43:4)
```

For some reason, the fork-ts-checker-webpack-plugin seems to be incompatible with SpeedMeasurePlugin.  You don't seem to have the same call above that references any specific plugins, but I would begin to question the way this is interacting with some of your other plugins in your webpack.config.

**Comment by kodemi** [comment] 2018-06-14 03:56
No, I don’t.

**Comment by johnnyreilly** [comment] 2018-06-14 05:35
Do you have a reproduction repo?

**Comment by samijaber** [comment] 2018-06-21 20:10
@kodemi I ran into the same issue, and it turned out I accidentally put the plugin in `webpack.resolve.plugins` instead of `webpack.plugins`. Moving it to the correct array in my webpack config resolved the issue for me!

**Comment by johnnyreilly** [comment] 2018-06-21 20:55
Thanks for reporting back! Super helpful for others 🌻♥️

**Comment by meatherly** [comment] 2019-03-07 19:54
I'm having a similar issue. trying to put together a repo for you guys. 
```
TypeError: Cannot read property 'options' of undefined
    at ForkTsCheckerWebpackPlugin.computeContextPath (/Users/michael.eatherly/workspace/compass/node_modules/fork-ts-checker-webpack-plugin/src/index.ts:132:25)
    at ForkTsCheckerWebpackPlugin.apply (/Users/michael.eatherly/workspace/compass/node_modules/fork-ts-checker-webpack-plugin/src/index.ts:258:21)
```
This is happening on version 1.0.0 for me. If I switch to version 0.5.2 it goes away. 
put if I manually set the tsconfig option with: `path.resolve("./tsconfig.json")` it works. but this is because it doesn't call `this.compiler.options` lol

Also I'm using a mono repo with `extends` in my tsconfig.json. not sure if that's a problem either. 

Hopefully I can create a test repo to recreate the problem.

**Comment by johnnyreilly** [comment] 2019-03-07 20:04
Might be worth you checking out the various alpha versions of the plugin so you can narrow down when the problem arose

See details of versions here: https://github.com/Realytics/fork-ts-checker-webpack-plugin/blob/master/CHANGELOG.md

Could be this: https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/214

**Comment by meatherly** [comment] 2019-03-07 20:25
@johnnyreilly Ah! thanks I didn't think about doing that and I had `^` on my package.json 🤕 
I started testing it and it was working all the way up until `v1.0.0-alpha.5` so that's the culprit! 
Thanks for your help!! I'll continue to use v1.0.0-alpha.4 until I or someone has time to dig into the issue.

**Comment by johnnyreilly** [comment] 2019-03-07 20:34
Awesome - if you did get the chance to look into this I'd greatly appreciate it. I'm guessing the issue lies somewhere in here: https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/204/files (the PR that lead to 1.0.0-alpha.5)

**Comment by roni-frantchi** [comment] 2019-04-18 07:22
This was a lifesaver https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/118#issuecomment-399227381 .  
Thanks @samijaber !

**Closed as completed** 2019-05-19 17:47 UTC
