### ISSUE TITLE
5.0.0-alpha.14 cannot import ForkTsCheckerWebpackPlugin as a namespaced import

### ISSUE THREAD

**Issue by jdanil** [TypeStrong/fork-ts-checker-webpack-plugin#433] opened 2020-05-29 06:02 UTC
## Current behavior
When importing `ForkTsCheckerWebpackPlugin` in a typescript file, the plugin cannot be imported via the namespace syntax (i.e. `import * as ForkTsCheckerWebpackPlugin from "fork-ts-checker-webpack-plugin"`).

Some workarounds to the namespace import include...
- direct import
  - `import { ForkTsCheckerWebpackPlugin } from "fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.js";`
- enabling `esModuleInterop` and using a default import
  - `import ForkTsCheckerWebpackPlugin from "fork-ts-checker-webpack-plugin`
- require without type definitions
  - `const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin')`

The current stable version of plugin declares a namespace for `ForkTsCheckerWebpackPlugin` (https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/master/src/index.ts). I suspect that's whats missing from the alpha version, manually editing the plugin's type definitions in my node_modules folder to include this namespace appears to resolve the issue.

## Expected behavior
Should be able to import the plugin via the namespace import `import * as ForkTsCheckerWebpackPlugin from "fork-ts-checker-webpack-plugin"`.

## Steps to reproduce the issue
1. `git clone`
1. `yarn install`
1. `cd packages/app`
1. `yarn start`
   - fails. cannot import module with namespace syntax.

## Issue reproduction repository
https://github.com/jdanil/fork-ts-checker-project-references

## Environment
 - **fork-ts-checker-webpack-plugin**: 5.0.0-alpha.14
 - **typescript**: 3.9.3
 - **eslint**: N/A
 - **webpack**: 4.43.0
 - **os**: Windows 10

**Comment by piotr-oles** [comment] 2020-06-01 17:20
I think it's not a bug - it's a breaking change :)
The reason why we use `export = ForkTsCheckerWebpackPlugin` is to follow the convention used by the webpack (this is the way they export built-in plugins). And as [TypeScript docs say](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require):
> When exporting a module using export =, TypeScript-specific import module = require("module") must be used to import the module.

I think this plugin should not workaround the intended behavior of the TypeScript.

**Comment by piotr-oles** [comment] 2020-06-02 08:19
Anyway - thank you for reporting this issue - I'm open for further discussion so don't hesitate to challenge my argumentation. I will close this issue for now ;)

**Closed as completed by piotr-oles** 2020-06-02 08:19 UTC
Labels: bug

**Comment by artyomtrityak** [comment] 2020-11-17 01:49
I want to follow up about this issue as it requires to config configuration file just for a single plugin

**Comment by piotr-oles** [comment] 2020-11-17 08:52
Please use `import ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin')` or enable `esModuleInterop` :)

**Comment by mdentremont** [comment] 2021-06-10 13:24
@piotr-oles Could you include the `import ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin')` to the readme? This is a pretty big gotcha for those that run into it 😄

**Comment by piotr-oles** [comment] 2021-06-11 05:51
I'm a little bit busy these days - feel free to open PR :)
