### ISSUE TITLE
Occasionally stops working

### ISSUE THREAD

**Issue by aaronjensen** [TypeStrong/fork-ts-checker-webpack-plugin#330] opened 2019-08-21 18:03 UTC
## Current behavior
Occasionally, after waking up from sleep, fork-ts-checker-webpack-plugin stop working. It will no longer emit any status (either type checking in progress or type errors). Restarting webpack fixes this.

## Expected behavior
I don't have to restart webpack.

## Steps to reproduce the issue

I'm not sure how to reproduce this 100%, it just happens sometimes. My configuration is minimal:

```
    new ForkTsCheckerWebpackPlugin({
      tsconfig: root('tsconfig.json'),
    })
```

I also use this, in case its relevant:

```
export TSC_WATCHFILE=UseFsEvents
```

## Issue reproduction repository

None

## Environment
 - **fork-ts-checker-webpack-plugin**: 1.5.0
 - **typescript**: 3.5.3
 - **tslint**: none
 - **webpack**: 4.39.2
 - **os**: macOS 10.14.6

**Comment by ypresto** [comment] 2019-09-17 10:44
In my environment it also stops without any output, with 100% CPU, and running even after Ctrl+C.
And always reproduces, but with `useTypescriptIncrementalApi: false` option it does not reproduce.

When I attached to service.js instance (added `--inspect-brk` to plugin's js code), it seems doing type ~check~ emit for TS file which references our most complex type declaration.

**Comment by ypresto** [comment] 2019-09-17 10:53
It seems a issue of typescript compiler for our case, because `tsc --watch` does not finish while `tsc` do.
https://github.com/microsoft/TypeScript/issues/25023

**Comment by johnnyreilly** [comment] 2019-09-17 12:39
@ypresto I think you may be experiencing this: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/236

**Comment by ypresto** [comment] 2019-09-17 14:46
@johnnyreilly Even when I prepend `TSC_WATCHFILE=UseFsEvents` to tsc command it does not finish, and inspector shows it is working hard (= not idle) on ast nodes. So our case looks different than watchfile one.

**Comment by thehappycoder** [comment] 2020-02-17 01:17
In one project, some code was added, which increased a production build from ~7mins to ~45mins. Setting `useTypescriptIncrementalApi` to `false` helped reducing it back.

**Comment by piotr-oles** [comment] 2020-05-23 19:19
@aaronjensen , @ypresto , @thehappycoder
Please try [fork-ts-checker-webpack-plugin@alpha](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/alpha) - I've published a new version which should resolve this issue 🚀
I will close this issue to clean-up the backlog. If this release didn't solve the issue, we can re-open this :)

**Closed as completed by piotr-oles** 2020-05-23 19:19 UTC
Labels: bug
