### ISSUE TITLE
Sometimes watch is using old Diagnostics

### ISSUE THREAD

**Issue by WolfspiritM** [TypeStrong/fork-ts-checker-webpack-plugin#362] opened 2019-11-26 02:54 UTC
## Current behavior
Sometimes when saving files quickly after another and possibly when many file watchers are active the ApiIncrementalChecker is outputing the previous Diagnostics.

## Expected behavior
Always use new diagnostics

## Steps to reproduce the issue
Change and save files with and without errors repeatedly causes it to randomly not displaying the error but old diagnostics.

## Possible solution
This might be a windows/os issue cause it's related to file watchers.
The reason is that webpack triggers a compile but the filewatcher of the CompilerHost didn't receive that change yet. Therefor the callback of the watched file is not triggered and no compilation happens. There is an if statement saying that if no compilation happened it's assumed to not be a related file to typescript therefore old diagnostics apply.

Possible solutions I can think of: Wait for a set time of ms until at least one change event happend (needs a timeout as unrelated files might have changed).

For tests I made a while loop around 
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/04581f4a8cc999563e9ba1c63bfee7efb97e380f/src/CompilerHost.ts#L193-L209
until at least one "item.callback" is triggered or 100ms are over. That fixed the problem but I feel like it's not a good solution.

A better approach I can think of is passing the changed files from webpack to that fileWatchers list and call the "callback" as long as the filepath matches, but I'm not familiar with webpack plugins and it might be a bit hard to pass that data down to the service.

## Environment
 - **fork-ts-checker-webpack-plugin**: master
 - **typescript**: ^3.0.1
 - **tslint**: ^5.11.0
 - **webpack**: ^5.0.0-alpha.5
 - **os**: Windows 10

**Comment by johnnyreilly** [comment] 2019-11-26 20:27
The `ApiIncrementalChecker` uses the underlying API in TypeScript to power the checking. I'm curious as to how webpack is the cause of the issue here; what's the "join" if you will between the TypeScript API and webpack and hence the cause of the issue do you think?

**Comment by WolfspiritM** [comment] 2019-11-26 20:38
@johnnyreilly Yes. However as far as I understand the watch callbacks are delayed until webpack triggers a build. All watch events are queued and pushed to webpack once with the forEach loop I mentioned above. The changes are queued here: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/04581f4a8cc999563e9ba1c63bfee7efb97e380f/src/CompilerHost.ts#L300-L305

Usually that is a single changed file however in some cases the webpack build triggers before that file watcher got triggered (which sometimes happens at least under windows) resulting in an empty list of changes so the forEach loop doesn't have any changes yet to forward to typescript. Afterwards the watcher is triggered and just queues the change for the next run so it needs a new trigger from webpack which then pushes two changes (the old and the new one (at least if this time the typescript watcher was quick enough)) to typescript.

**Comment by johnnyreilly** [comment] 2019-11-26 22:06
Hmmmm.... I'd be interested in trying out some mitigation strategies here. If we could do it behind a feature flag then we could release it, get a broader group of people to try it and graduate it to the default if it works. What do you think?

**Comment by boxmein** [comment] 2019-12-03 01:03
I'm experiencing the same issue as well. When saving a file, noticing a mistake, quickly editing and saving it again, often times the first error is shown even after I've already made the changes. The error message highlights the line that the error does not exist on any more.

**Comment by pelotom** [comment] 2019-12-03 07:43
I've been seeing this too for a while now, and it's not restricted to windows (I'm on a Mac). It's pretty reliably reproducible in my large-ish CRA-based app. I would guess that in smaller codebases it may be harder to reproduce because compilation usually finishes before you can fix/introduce an error and save again.

**Comment by johnnyreilly** [comment] 2019-12-03 08:31
Yeah - I've experienced it too. I don't have time to look into this myself but I'd welcome people experimenting with ways to tackle it. Some kind of debouncing mechanism might work

**Comment by piotr-oles** [comment] 2020-02-05 11:07
It will be fixed with the 5.0.0 release - this plugin will use only webpack's watcher to avoid race conditions :)

**Comment by piotr-oles** [comment] 2020-05-23 19:14
@WolfspiritM
Please try [`fork-ts-checker-webpack-plugin@alpha`](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/alpha) - I've published a new version which should resolve this issue 🚀

**Comment by piotr-oles** [comment] 2020-05-23 19:15
I will close this issue to clean-up the backlog. If it wasn't resolved with this version, we can re-open this issue :)

**Closed as completed by piotr-oles** 2020-05-23 19:15 UTC
Labels: bug, help wanted
