### ISSUE TITLE
eslint emitWarning option

### ISSUE THREAD

**Issue by olee** [TypeStrong/fork-ts-checker-webpack-plugin#374] opened 2020-01-12 19:39 UTC
eslint-loader has an option named `emitWarning` to make all errors warnings instead, to help during development so hot-updates etc. do not fail.
It would be great to allow setting this option in fork ts checker as well.

**Comment by johnnyreilly** [comment] 2020-01-12 21:07
Is that configurable using `eslintOptions`? Possible dupe of https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/346

**Comment by piotr-oles** [comment] 2020-05-23 19:53
@olee
Please try [fork-ts-checker-webpack-plugin@alpha](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/alpha) - I've published a new version which should resolve this issue 🚀 (there is an option to pass eslint options and another option to set issues predicates)
I will close this issue to clean-up the backlog. If this release didn't solve the issue, we can re-open this :)

**Closed as completed by piotr-oles** 2020-05-23 19:53 UTC
Labels: enhancement

**Comment by danylkaaa** [comment] 2021-05-31 16:07
Hello! As I found, you just pass eslint options to eslint CLI. So, eslint does not have build-in CLI option to emit all errors as warnings.
 `eslint-webpack-plugin` does this with custom processor for CLI errors
https://github.com/webpack-contrib/eslint-webpack-plugin/blob/c12e7be0be49f95fa8f2d9ae354acba3bd412b5c/src/linter.js#L202

Could you pls add some kind of preprocessor for eslint errors, that will allow to work with HMR even if there is eslint error?

**Comment by piotr-oles** [comment] 2021-06-01 06:11
Hi! :) You can use `issues` hook: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#plugin-hooks . This is `SyncWaterfallHook` so you can return modified list of issues. You can for example map all eslint issues to be with severity = 'warning'
